---
always_allow_html: true
output: github_document
---

# Intraoperative adverse events as a risk factor for local recurrence of rectal cancer after resection surgery                        

Sophia Waldenstedt (S.W.) 1,2, David Bock (D.B.)1, Eva Haglind (E.H.)1-2, Björn Sjöberg1 (B.S.) and Eva Angenete (E.A.)1,2.

1 Department of Surgery, SSORG – Scandinavian Surgical Outcomes Research Group, Institute of Clinical Sciences, Sahlgrenska Academy, University of Gothenburg, Gothenburg, Sweden.
2 Region Västra Götaland, Sahlgrenska University Hospital, Department of Surgery, Gothenburg, Sweden.

#  Description                                                    
A retrospective population-based cohort study, including all patients in Region Västra Götaland, Sweden, who had undergone primary resection surgery for rectal cancer diagnosed from 2010 to 2014, registered in the Swedish Colorectal Cancer Registry (SCRCR). 

This study was approved by the Ethical Review Board of Gothenburg, Sweden (715-17). The study is registered at Clinical Trials NCT04406974.             

*Individual patient level data can not be publicly available or shared due to restrictions in the ethics approval agreement*            
# R code                             
The following R program code programs for data management and statistical analysis are available:                      
**1. _Datafix_script**                                       
Derive analysis set.                            
**2. I_CompetingRisks_script**                                       
Competing risk analysis.                               
**3.II_Variable importance_script**                                                      
Variable importance by bootstrap evaluation of variable selection by LASSO Cox regression.                            
**4.III_Prediction_script**                                     
Evaluation of predictive performance by internal validation with bias-correction by boostrapping.                
Graphical assessment of calibration.                            


